#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}

trap onExit EXIT

docker build -t eoepca/mkdocs-material .

exec docker run --name mkdocs-serve --rm -it \
  -p 8000:8000 \
  -v ${PWD}:/docs \
  eoepca/mkdocs-material \
  serve --dev-addr 0.0.0.0:8000